---
title: "Henderson-Hasselbalch calculations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)


```


## Reversible Protonation

Bonds to hydrogen can often break to form a proton and the resulting base. Not all bonds to hydrogen have the same strength although molecules that are prone to break are often called *acids*. In biochemistry, there are two main types: *strong* and *weak*. Strong acids are ones that are fully dissociated in water into the proton and the conjugate base of the acid. Weak acids are ones that are only partially dissociated within the range of pH values 1 to 14. These molecules are useful for serving as *buffers* or molecules that can maintain pH within a specified range. Each weak acid or buffer has a distinct pH range where it is most effective. This range called the *buffer range* is $\pm$ 1 pH unit of the *pK~A~* value. 

The pK~A~ value is:

$$ pK_A = -log(K_A) $$

the acid dissociation constant or K~A~ is:

$$ K_A = \frac{[H^+][A^-]}{[HA]} $$

Thus, the pK~A~ value relates to the equilibrium constant showing the breakdown of acid into the proton and the conjugate base. As the concentration of conjugate base and proton increase, the K~A~ value gets larger and the pK~A~ value gets smaller. Practically this makes sense as acids that are more likely to release a proton are considered stronger and have lower pK~A~  values. The strong acid, hydrochloric acid (HCl), has a pK~A~ of -7 while ammonium (NH~4~^+^) has a pK~A~ of 9 ([ref](https://www2.onu.edu/~b-myers/organic/2511_Files/Chapter3-pKa%20table.pdf)). Because this is on a log scale that means that there are 16 orders of magnitude (10^16^) difference in the K~A~ values for these two acids. Practically what this means is that HCl is completely dissociated in solution, while ammonium is partially dissociated and the degree of dissociation depends on the pH value. 

## The Henderson-Hasselbalch equation

$$ pH = pK_A + log\frac{base}{acid} $$
The *Henderson-Hasselbalch equation* shown above is one of the fundamental equations in biochemistry and relates the amount of the protonated (acid) and deprotonated (base) forms of a weak acid and the $-log(K_A)$ or pK~A~ to the pH value. Given any two of those terms, one can calculate the third term in the equation. One key point to make is that when the [base] = [acid], then pH = pK~A~. 

The uses for this in "real-life" are precisely making buffered solutions at a specific pH using the amount of base and acid of a molecule, eliminating the need for using strong acids or bases to adjust the pH. While this seems to be an esoteric use, in industrial settings being able to mix specific amonuts of weak acid and conjugate base and get to an exact value saves time and money. 

### Using the app

The app associated with this document allows for setting of the pH and pK~A~ to observe this changes the relative amounts of acid and conjugate base in solution. This is illustrated in the *left* and *center* panels which show a simulated solution of base and acid and a quantitation of the number of molecules out of a thousand in that solution. The *right* panel shows the pH value relative to the pK~A~ as if this were a titration experiment. Because weak acids can be buffers $\pm$ 1 pH unit of the *pK~A~* value, this panel shows whether the solution is within the buffer range of the weak acid or at one of the extremes. As the pH and the pK~A~ value get further apart the red dot get smaller and more transparent meaning the acid has less ability to buffer at that pH value.

